# Generated by Django 4.2.6 on 2024-08-14 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_remove_usuario_date_joined_remove_usuario_email_and_more'),
        ('comentarios', '0002_comentarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='usuario.usuario'),
        ),
    ]
