# Generated by Django 5.0.4 on 2024-07-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor')], default='ALUNO', max_length=15, verbose_name='Tipo de Usuário'),
        ),
    ]
