# Generated by Django 4.2.6 on 2024-07-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='turma',
        ),
    ]
