# Generated by Django 4.2.6 on 2024-07-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('professor', 'Professor'), ('aluno', 'Aluno')], max_length=10, null=True),
        ),
    ]
