# Generated by Django 4.2.6 on 2024-08-13 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_usuario_tipo_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='turma',
        ),
    ]
