# Generated by Django 4.2.6 on 2024-08-13 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='turma',
        ),
    ]
