# Generated by Django 4.2.6 on 2024-08-13 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_experimento_usuario'),
        ('atividades', '0002_remove_atividade_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='experimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.experimento'),
            preserve_default=False,
        ),
    ]
