# Generated by Django 4.2.6 on 2024-08-14 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_remove_experimento_participantes_and_more'),
        ('turmas', '0013_remove_turma_matricula_usuarioturma'),
        ('atividades', '0003_atividade_experimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='turmas.usuarioturma'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='experimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='sistema.experimento'),
        ),
    ]
