# Generated by Django 4.2.6 on 2024-08-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0004_atividade_responsavel_alter_atividade_experimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='arquivo',
            field=models.FileField(upload_to='media/'),
        ),
    ]
