# Generated by Django 4.2.6 on 2024-08-13 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bate_papo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bate_papo',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bate_papo',
            name='mensagem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
