# Generated by Django 4.2.6 on 2024-08-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bate_papo', '0002_bate_papo_data_bate_papo_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bate_papo',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
