# Generated by Django 4.2.6 on 2024-08-14 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0013_remove_turma_matricula_usuarioturma'),
        ('bate_papo', '0003_alter_bate_papo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='bate_papo',
            name='usuario_turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bate_papo', to='turmas.usuarioturma'),
        ),
    ]
