# Generated by Django 4.2.6 on 2024-08-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0015_turma_matricula'),
        ('bate_papo', '0004_bate_papo_usuario_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bate_papo',
            name='usuario_turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turmas.usuarioturma'),
        ),
    ]
