# Generated by Django 4.2.6 on 2024-08-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bate_papo', '0005_alter_bate_papo_usuario_turma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bate_papo',
            old_name='usuario_turma',
            new_name='usuarioturma',
        ),
    ]
