# Generated by Django 4.2.6 on 2024-08-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bate_papo', '0006_rename_usuario_turma_bate_papo_usuarioturma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bate_papo',
            name='mensagem',
            field=models.CharField(max_length=100),
        ),
    ]
