# Generated by Django 4.2.6 on 2024-08-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bate_papo', '0007_alter_bate_papo_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bate_papo',
            name='mensagem',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
