# Generated by Django 4.2.6 on 2024-07-29 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema', '0002_experimento_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimento',
            name='usuario',
            field=models.ManyToManyField(related_name='experimentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experimento',
            name='participantes',
            field=models.CharField(max_length=100),
        ),
    ]
