# Generated by Django 4.2.6 on 2024-07-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_experimento_usuario_alter_experimento_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='participantes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
