# Generated by Django 4.2.6 on 2024-07-30 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0009_remove_turma_usuario'),
        ('sistema', '0004_alter_experimento_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimento',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experimentos', to='turmas.turma'),
        ),
    ]
