# Generated by Django 4.2.6 on 2024-08-13 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_experimento_turma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimento',
            old_name='localização',
            new_name='localizacao',
        ),
        migrations.RemoveField(
            model_name='experimento',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='experimento',
            name='usuario',
        ),
    ]
