# Generated by Django 4.2.6 on 2024-08-13 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema', '0007_experimento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimento', to=settings.AUTH_USER_MODEL),
        ),
    ]
