# Generated by Django 4.2.6 on 2024-08-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_alter_experimento_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimento',
            name='usuario',
        ),
    ]
