# Generated by Django 4.2.6 on 2024-08-13 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0012_alter_turma_matricula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema', '0010_experimento_turma_experimento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimento', to='turmas.turma'),
        ),
        migrations.AlterField(
            model_name='experimento',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experimento', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
