# Generated by Django 4.2.6 on 2024-08-13 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turmas', '0012_alter_turma_matricula'),
        ('sistema', '0011_alter_experimento_turma_alter_experimento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.turma'),
        ),
        migrations.AlterField(
            model_name='experimento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
