# Generated by Django 4.2.6 on 2024-08-14 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0013_remove_turma_matricula_usuarioturma'),
        ('sistema', '0012_alter_experimento_turma_alter_experimento_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimento',
            name='participantes',
        ),
        migrations.RemoveField(
            model_name='experimento',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='experimento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='experimento',
            name='usuarioturma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turmas.usuarioturma'),
        ),
    ]
