# Generated by Django 4.2.6 on 2024-07-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_atividade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atividade',
        ),
    ]
