# Generated by Django 4.2.6 on 2024-07-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0005_remove_turma_alunos_remove_turma_professor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
