# Generated by Django 4.2.6 on 2024-07-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0006_turma_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='usuario',
        ),
    ]
