# Generated by Django 4.2.6 on 2024-07-29 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0008_turma_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='usuario',
        ),
    ]
