# Generated by Django 4.2.6 on 2024-07-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0009_remove_turma_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
