# Generated by Django 4.2.6 on 2024-08-13 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turmas', '0010_alter_turma_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='matricula',
            field=models.ManyToManyField(related_name='turmas', to=settings.AUTH_USER_MODEL),
        ),
    ]
