# Generated by Django 4.2.6 on 2024-08-14 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_remove_usuario_date_joined_remove_usuario_email_and_more'),
        ('turmas', '0013_remove_turma_matricula_usuarioturma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioturma',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
