# Generated by Django 4.2.6 on 2024-08-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_remove_usuario_date_joined_remove_usuario_email_and_more'),
        ('turmas', '0014_alter_usuarioturma_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='matricula',
            field=models.ManyToManyField(through='turmas.UsuarioTurma', to='usuario.usuario'),
        ),
    ]
