# Generated by Django 4.2.6 on 2024-08-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0015_turma_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
